const routers = {
    home: '/',
    community: '/community',
    detail: '/detail',
    discovery: '/discovery',
    comming: '/comming',
    friends: '/friends',
    parties: 'parties',
    media: '/media',
    genre: '/genre',
    nation: '/nation',
    series: '/series',
    odd: '/odd',
    setting: '/setting',
    loggin: '/loggin',
    Logout: '/Logout',
    video: '/phim/:slug',
    detailVideo: '/phim/:slug/:num',
}
export default routers
